# Generated by Django 3.0.2 on 2021-07-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
