# Generated by Django 3.0.2 on 2021-07-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210701_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='total_amount',
            new_name='amount',
        ),
    ]
