# Generated by Django 3.0.2 on 2021-07-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20210701_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tranzaksiya sababi (izoh)'),
        ),
    ]
