# Generated by Django 3.0.2 on 2021-07-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_transaction_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='paycom_time_datetime',
            new_name='time_datetime',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan vaqti:'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='perform_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqti:'),
        ),
    ]
