# Generated by Django 3.0.2 on 2021-07-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_transaction_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.IntegerField(choices=[(0, 'Инвойсе создан'), (1, 'Транзакция создан'), (2, 'Инвойсе оплачен'), (-1, 'Транзакция отменен'), (-2, 'Транзакция отменена после завершения')], default=0),
        ),
    ]
