# Generated by Django 3.0.2 on 2021-07-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20210707_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order_type',
        ),
    ]
