# Generated by Django 3.0.2 on 2021-06-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatedcourse',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='course',
            name='paid',
        ),
    ]
