# Generated by Django 3.0.2 on 2021-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210805_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority', 'id'), 'verbose_name_plural': '       Categories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('priority', 'id'), 'verbose_name': 'Course', 'verbose_name_plural': '     Courses'},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.SmallIntegerField(default=0, help_text='the higher the number, the more priority'),
        ),
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.SmallIntegerField(default=0, help_text='the higher the number, the more priority'),
        ),
    ]
