# Generated by Django 3.0.2 on 2021-08-25 09:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210810_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-priority', 'id'), 'verbose_name_plural': '       Categories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-priority', 'id'), 'verbose_name': 'Course', 'verbose_name_plural': '     Courses'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Lesson Description'),
        ),
    ]
