# Generated by Django 3.0.2 on 2021-06-09 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Answer text')),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Question Title')),
                ('technique', models.IntegerField(choices=[(0, 'Single Choice'), (1, 'Multiple Choice'), (2, 'True/False')], default=0, verbose_name='Type of Question')),
                ('type_of_test', models.IntegerField(choices=[(0, 'Interval Test'), (1, 'Final Test')], default=0, verbose_name='Type of Test')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': ' Questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Quiz Name')),
                ('duration', models.IntegerField(default=40, help_text='Duration of the quiz in minutes', verbose_name='Test duration')),
                ('required_score_to_pass', models.IntegerField(default=80, help_text='Required score to pass the quiz (%)', verbose_name='Required score')),
                ('chances', models.SmallIntegerField(default=5, verbose_name='Chances count')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Blocked')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.Topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': '  Quizzes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('chances_left', models.SmallIntegerField(default=5, verbose_name='Chances left')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takers', to='quiz.Quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_takers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Taker',
                'verbose_name_plural': 'Quiz Takers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsersAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_answers', to='quiz.Answer', verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answers', to='quiz.Question', verbose_name='Question')),
                ('quiz_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.QuizTaker', verbose_name='Quiz Taker')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.Question'),
        ),
    ]
