# Generated by Django 3.0.2 on 2021-06-09 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210609_1444'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_quiz', to='courses.Course', verbose_name='Course (if quiz is final)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.Topic', verbose_name='Topic (if quiz is not final)'),
        ),
    ]
