# Generated by Django 3.0.2 on 2021-06-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210609_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_blocked',
        ),
    ]
