# Generated by Django 3.0.2 on 2021-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='users_answers', to='quiz.Answer', verbose_name='Answer'),
        ),
    ]
