# Generated by Django 3.0.2 on 2021-07-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210713_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='unlock_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Unlock quiz at'),
        ),
        migrations.AlterField(
            model_name='usersanswer',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='users_answers', to='quiz.Answer', verbose_name='Answers'),
        ),
    ]
