# Generated by Django 3.0.2 on 2021-07-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210609_1444'),
        ('quiz', '0005_auto_20210714_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='certificated_course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.CertificatedCourse', verbose_name='Certificated course (if quiz for them)'),
        ),
    ]
