# Generated by Django 3.0.2 on 2021-08-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_certificated_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='certificated_courses',
        ),
        migrations.RemoveField(
            model_name='cartcourse',
            name='certificated_course',
        ),
    ]
