# Generated by Django 3.0.2 on 2021-08-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210810_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-id',)},
        ),
    ]
